config/routes.rb
Distribution::Application.routes.draw do
  resources :technicians

  resources :work_orders

  resources :posts

  get "home/index"

  root :to => "home#index"

end

app/models/technician.rb
class Technician < ActiveRecord::Base

end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  # GET /technicians
  # GET /technicians.xml
  def index
    @technicians = Technician.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @technicians }
    end
  end

  # GET /technicians/1
  # GET /technicians/1.xml
  def show
    @technician = Technician.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @technician }
    end
  end

  # GET /technicians/new
  # GET /technicians/new.xml
  def new
    @technician = Technician.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @technician }
    end
  end

  # GET /technicians/1/edit
  def edit
    @technician = Technician.find(params[:id])
  end

  # POST /technicians
  # POST /technicians.xml
  def create
    @technician = Technician.new(params[:technician])

    respond_to do |format|
      if @technician.save
        format.html { redirect_to(@technician, :notice => 'Technician was successfully created.') }
        format.xml  { render :xml => @technician, :status => :created, :location => @technician }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @technician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /technicians/1
  # PUT /technicians/1.xml
  def update
    @technician = Technician.find(params[:id])

    respond_to do |format|
      if @technician.update_attributes(params[:technician])
        format.html { redirect_to(@technician, :notice => 'Technician was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @technician.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /technicians/1
  # DELETE /technicians/1.xml
  def destroy
    @technician = Technician.find(params[:id])
    @technician.destroy

    respond_to do |format|
      format.html { redirect_to(technicians_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/technicians/_form.html.erb
<%= form_for(@technician) do |f| %>
  <% if @technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
      <% @technician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :long_name %><br />
    <%= f.text_field :long_name %>
  </div>
  <div class="field">
    <%= f.label :recent_count %><br />
    <%= f.text_field :recent_count %>
  </div>
  <div class="field">
    <%= f.label :recent_ram_count %><br />
    <%= f.text_field :recent_ram_count %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :ram_count %><br />
    <%= f.text_field :ram_count %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technicians/edit.html.erb
<h1>Editing technician</h1>

<%= render 'form' %>

<%= link_to 'Show', @technician %> |
<%= link_to 'Back', technicians_path %>

app/views/technicians/index.html.erb
<h1>Listing technicians</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Long name</th>
    <th>Recent count</th>
    <th>Recent ram count</th>
    <th>Count</th>
    <th>Ram count</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @technicians.each do |technician| %>
  <tr>
    <td><%= technician.name %></td>
    <td><%= technician.long_name %></td>
    <td><%= technician.recent_count %></td>
    <td><%= technician.recent_ram_count %></td>
    <td><%= technician.count %></td>
    <td><%= technician.ram_count %></td>
    <td><%= technician.active %></td>
    <td><%= link_to 'Show', technician %></td>
    <td><%= link_to 'Edit', edit_technician_path(technician) %></td>
    <td><%= link_to 'Destroy', technician, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Technician', new_technician_path %>

app/views/technicians/new.html.erb
<h1>New technician</h1>

<%= render 'form' %>

<%= link_to 'Back', technicians_path %>

app/views/technicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @technician.name %>
</p>

<p>
  <b>Long name:</b>
  <%= @technician.long_name %>
</p>

<p>
  <b>Recent count:</b>
  <%= @technician.recent_count %>
</p>

<p>
  <b>Recent ram count:</b>
  <%= @technician.recent_ram_count %>
</p>

<p>
  <b>Count:</b>
  <%= @technician.count %>
</p>

<p>
  <b>Ram count:</b>
  <%= @technician.ram_count %>
</p>

<p>
  <b>Active:</b>
  <%= @technician.active %>
</p>


<%= link_to 'Edit', edit_technician_path(@technician) %> |
<%= link_to 'Back', technicians_path %>