config/routes.rb
Distribution::Application.routes.draw do
  resources :technicians

  resources :work_orders

  resources :posts

  get "home/index"

  root :to => "home#index"

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
def validate
  if number.nil?
      errors.add_to_base "No number entered" if number.nil?
  else
     # errors.add_to_base "Work Order number must be at least 60,000 and an integer" if number < 60000
     # errors.add_to_base "Is this work order from the far future? W/O must be under 200,000" if number > 200000
  end
end

end
#validates :number, :presence => true,
#            :length => { :minimum => 6 }

def assign_technician
  # if self.ramupgrade == true do
  #   end
  id = find_next()
  @technician = Technician.find(id)
  self.technician = id
  if @technician.count.nil?
    @technician.count = 0
  end
  count = @technician.count + 1
  @technician.update_attributes(:count => count)
  self.assigned = true
end


def find_next
  # This code finds the lowest technician assigned to the work orders over the last day
  # and is also present today
  technicians_present = technicians_present_today()
  lowest = find_work_order_count_yesterday(1)
  # lowest_id = 0
  # yesterdayCount = 0
  for i in technicians_present do
    yesterdayCount = find_work_order_count_yesterday(i)
    if yesterdayCount <= lowest
      lowest = yesterdayCount
      lowest_id = i
    end
  end
  if lowest_id == 0 or lowest_id.nil?
    # This is my 'error code' for not being able to assign a technician
    lowest_id = 4
  end
  return lowest_id
  
  # This is deprecated code that was just used for testing, pretty worthless really
  # @technicians = Technician.find(:all, :order => "count ASC")
  #  return @technicians[0].id
end

def find_work_order_count_yesterday(technicianID)
  @work_orders = WorkOrder.find(:all, :conditions => ["DATE(created_at) BETWEEN ? AND ? AND technician = ?", Time.now.midnight-1.day, Time.now.midnight, technicianID])
  return @work_orders.size
end

def find_work_order_count_two_days_ago(technicianID)
  @work_orders = WorkOrder.find(:all, :conditions => ["DATE(created_at) BETWEEN ? AND ? AND technician = ?", Time.now.midnight-2.day, Time.now.midnight-1.day, technicianID])
  return @work_orders.size
end

def toname
  result = case self.technician
  when "0" then return "Not assigned"
  when "1" then return "XBG"
  when "2" then return "XJR"
  when "3" then return "XKU"
  end
  return result
end

# => Sunday is day 0, Saturday Day 6.
# => ID 1 = Ben, In from Thursday to Monday
# => ID 2 = Jay, In from Sunday to Thursday
# => ID 3 = Kyle, In from Tuesday to Saturday
def technicians_present_today()
  wday = Time.now.wday
  result = case wday
     when 0..1 then ["2","1"]
     when 2..3 then ["3","2"]
     when 4 then ["1","3","2"]
     when 5..6 then ["3","1"]
   end
   return result
end

def technician_first_day(technicianID)
  result = case technicianID
    when 1 then "5"
    when 2 then "0"
    when 3 then "2"
  end
return result
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  # GET /work_orders
  # GET /work_orders.xml
  def index
    @work_orders = WorkOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @work_orders }
    end
  end

  # GET /work_orders/1
  # GET /work_orders/1.xml
  def show
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work_order }
    end
  end

  # GET /work_orders/new
  # GET /work_orders/new.xml
  def new
    @work_order = WorkOrder.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work_order }
    end
  end
  
  # GET /work_orders/1/edit
  def edit
    @work_order = WorkOrder.find(params[:id])
  end

  # POST /work_orders
  # POST /work_orders.xml
  def create
    @work_order = WorkOrder.new(params[:work_order])
    #This will call the private method in the work order to get it to assign 
    #itself a technician. Kind of hack-ey but it works
    @work_order.send(:assign_technician)
    respond_to do |format|
      if @work_order.save
        format.html { redirect_to(@work_order, :notice => 'Work order was successfully created.') }
        format.xml  { render :xml => @work_order, :status => :created, :location => @work_order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_orders/1
  # PUT /work_orders/1.xml
  def update
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      if @work_order.update_attributes(params[:work_order])
        format.html { redirect_to(@work_order, :notice => 'Work order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /work_orders/1
  # DELETE /work_orders/1.xml
  def destroy
    @work_order = WorkOrder.find(params[:id])
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to(work_orders_url) }
      format.xml  { head :ok }
    end
  end
  
  def assign
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      if @work_order.update_attributes(params[:work_order])
        format.html { redirect_to(@work_order, :notice => 'Work order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.erb
<%= form_for(@work_order) do |f| %>
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :assigned %><br />
    <%= f.check_box :assigned %>
  </div>
  <div class="field">
    <%= f.label :ramupgrade %><br />
    <%= f.check_box :ramupgrade %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="field">
	<%= f.label :created_at %><br />
	<%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :technician %><br />
	<%= f.select(:technician, [["XBG", 1],["XJR", 2],["XKU", 3]], {:include_blank => true} )%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_orders/edit.html.erb
<h1>Editing work_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_order %> 
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<h1>Listing work_orders</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Assigned</th>
    <th>Ramupgrade</th>
    <th>Details</th>
    <th>Technician</th>
    <th>Created At</th>
    <th></th>
    <th></th>
	<th></th>
  </tr>

<% @work_orders.each do |work_order| %>
  <tr>
    <td><%= work_order.number %></td>
    <td><%= work_order.assigned %></td>
    <td><%= work_order.ramupgrade %></td>
    <td><%= work_order.details %></td>
    <td><%= work_order.send(:toname) %></td>
	<td><%= work_order.created_at.in_time_zone('Pacific Time (US & Canada)').strftime("%I:%M%p on %m/%d/%Y") %></td>
    <td><%= link_to 'Show', work_order %></td>
    <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
    <td><%= link_to 'Destroy', work_order, :confirm => 'Are you sure?', :method => :delete %></td>
	<!-- <td><%= link_to 'Assign', edit_work_order_path(work_order) %></td> -->
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Work order', new_work_order_path %>

app/views/work_orders/new.html.erb
<h1>New work_order</h1>

<%= render 'form' %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @work_order.number %>
</p>

<p>
  <b>Assigned:</b>
  <%= @work_order.assigned %>
</p>

<p>
  <b>Ramupgrade:</b>
  <%= @work_order.ramupgrade %>
</p>

<p>
  <b>Details:</b>
  <%= @work_order.details %>
</p>

<p>
  <b>Technician:</b>
  <%= @work_order.send(:toname) %>
</p>



<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>